name: GitHub CI

on: push

jobs:
  ci-build:
    strategy:
      fail-fast: false
      matrix:
        cfg:

        - name: Linux x64
          os: ubuntu-16.04
          target: linux

        - name: Mingw x64 (cross compile)
          os: ubuntu-latest
          target: mingw

        - name: Mac
          os: macos-latest
          target: mac

    name: ${{ matrix.cfg.name }}
    runs-on: ${{ matrix.cfg.os }}
    steps:

    - name: Context in env
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
        JOB_CONTEXT: ${{ toJson(job) }}
      run: ''

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build with bash
      shell: bash
      run: ${{ github.workspace }}/.github/scripts/ci-build.sh 2>&1
      env:
        CI_NAME: ${{ matrix.cfg.name }}
        CI_OS: ${{ matrix.cfg.os }}
        CI_TARGET: ${{ matrix.cfg.target }}
